# Keuken kast light: Turn on if coming home between 7 and 0:30 
- alias: "Keuken kast light: Turn on if coming home"
  trigger:
    platform: state
    entity_id: device_tracker.inash, device_tracker.manon, device_tracker.manon_phone, device_tracker.hans, device_tracker.hans_oneplus
    from: 'not_home'
    to: 'home'
  condition:
     condition: and
     conditions:
       - condition: or
         conditions:
           - condition: time
             after: '07:00:00'
           - condition: time
             before: '00:30:00'
  action:
    service: light.turn_on
    entity_id: light.Keuken_kast

########################################################################
# Keuken kast light: Turn on if 7 hour and home
- alias: "Keuken kast light: Turn on if 7 hour and home"
  trigger:
    platform: time
    hours: 7
    minutes: 0
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: device_tracker.inash
            state: 'home'
          - condition: state
            entity_id: device_tracker.manon
            state: 'home'
          - condition: state
            entity_id: device_tracker.manon_phone
            state: 'home'
          - condition: state
            entity_id: device_tracker.hans_oneplus
            state: 'home'
  action:
    service: light.turn_on
    entity_id: light.Keuken_kast

########################################################################
# Keuken kast light: Turn off if not home between 7 and 0:30
- alias: "Keuken kast light: Turn off if home"
  trigger:
    platform: state
    entity_id: device_tracker.inash, device_tracker.manon, device_tracker.manon_phone, device_tracker.hans, device_tracker.hans_oneplus
    from: 'home'
    to: 'not_home'
  condition:
     condition: and
     conditions:
       - condition: or
         conditions:
           - condition: time
             after: '07:00:00'
           - condition: time
             before: '00:30:00'
  action:
    service: light.turn_off
    entity_id: light.Keuken_kast
